### NumPy Advanced Question 1
#### Problem:
You are given a NumPy array of shape (6, 6) containing random integers between 0–100.
1. Find the row-wise maximum and column-wise mean.
2. Normalize the array values to a range between 0 and 1.
3. Replace all values greater than 0.75 with 1 and all values less than 0.25 with 0.

In [7]:
import numpy as np
np.random.seed(42)

In [9]:
arr=np.random.randint(0,100,(6,6))
arr

array([[51, 92, 14, 71, 60, 20],
       [82, 86, 74, 74, 87, 99],
       [23,  2, 21, 52,  1, 87],
       [29, 37,  1, 63, 59, 20],
       [32, 75, 57, 21, 88, 48],
       [90, 58, 41, 91, 59, 79]])

In [13]:
# row wise max
np.max(arr,axis=0)

array([90, 92, 74, 91, 88, 99])

In [12]:
# column wise mean
arr.mean(axis=1)

array([51.33333333, 83.66666667, 31.        , 34.83333333, 53.5       ,
       69.66666667])

In [14]:
# normalize between 0 and 1
arr_min=np.min(arr)
arr_max=np.max(arr)
np_norm = (arr - np.mean(arr))/(arr_max-arr_min)

In [15]:
np_norm

array([[-0.03061224,  0.3877551 , -0.40816327,  0.17346939,  0.06122449,
        -0.34693878],
       [ 0.28571429,  0.32653061,  0.20408163,  0.20408163,  0.33673469,
         0.45918367],
       [-0.31632653, -0.53061224, -0.33673469, -0.02040816, -0.54081633,
         0.33673469],
       [-0.25510204, -0.17346939, -0.54081633,  0.09183673,  0.05102041,
        -0.34693878],
       [-0.2244898 ,  0.21428571,  0.03061224, -0.33673469,  0.34693878,
        -0.06122449],
       [ 0.36734694,  0.04081633, -0.13265306,  0.37755102,  0.05102041,
         0.25510204]])

In [21]:
np_norm[np_norm>0.75]=1
np_norm[np_norm<0.25]=0
np_norm

array([[0.        , 0.3877551 , 0.        , 0.        , 0.        ,
        0.        ],
       [0.28571429, 0.32653061, 0.        , 0.        , 0.33673469,
        0.45918367],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.33673469],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.34693878,
        0.        ],
       [0.36734694, 0.        , 0.        , 0.37755102, 0.        ,
        0.25510204]])

#### Question 2: Efficient Matrix Operations
You’re given two large 1000×1000 NumPy arrays A and B. Perform the following efficiently (without explicit loops):
1. Compute the dot product of A and B.
2. Compute the element-wise multiplication of A and B.
3. Extract the main diagonal of the dot product matrix.
4. Compute the sum of all diagonal elements (trace).
5. Verify whether the dot product matrix is symmetric.

In [23]:
arr1=np.random.randn(1000,1000)
arr2=np.random.randn(1000,1000)

In [24]:
arr1.shape

(1000, 1000)

In [ ]:
# dot product
arr3=np.dot(arr1, arr2)

In [ ]:
# element wise multiplication
arr4=np.multiply(arr1, arr2)

In [ ]:
# main diagonal
arr4=np.diag(arr3)
arr4.shape

(1000,)

In [33]:
# sum of trace
arr5=np.sum(np.diag(arr4))
arr5

-1750.901455310185

In [34]:
# summetric check
np.allclose(arr3, arr3.T)

False

#### Question 3: Broadcasting and Normalization

You’re given a 2D NumPy array X of shape (1000, 50) where each row represents a sample and each column represents a feature. Perform the following tasks using broadcasting (no loops allowed):

1. Normalize each column (subtract mean and divide by standard deviation → z-score normalization).

2. Compute the column-wise min–max scaling (scale each column to [0,1]).

3. Add a bias column of all ones as the first column (so new shape becomes (1000, 51)).

4. Compute the cosine similarity between the first row and all other rows.

In [36]:
arr=np.random.randint(0,100, (1000,50))

In [42]:
arr

array([[36, 78, 86, ..., 48, 97, 14],
       [55, 47, 36, ..., 79, 75, 16],
       [67, 85, 58, ..., 58, 50, 76],
       ...,
       [89, 11, 80, ..., 55, 67, 98],
       [54, 67, 54, ...,  1, 68, 21],
       [90, 30, 24, ..., 96, 69, 76]])

In [ ]:
# standarddization on each column
arr_stand=(arr-arr.mean(axis=0))/arr.std(axis=0)
arr_stand.mean(0)

array([48.8506233 , 47.15087265, 48.37246921, 47.47013802, 46.67933692,
       46.36340838, 47.06248337, 48.0020691 , 47.77072463, 47.23300696,
       46.67731913, 48.33675619, 48.4038711 , 48.0689266 , 47.71800707,
       48.06429907, 48.3389872 , 47.55946613, 48.13081522, 46.38688455,
       46.99887004, 48.73375059, 46.83374508, 45.95776805, 47.22363433,
       47.7422391 , 49.11688931, 48.73644487, 47.92550514, 47.65819038,
       48.12286574, 48.51831895, 46.29450122, 48.42539424, 48.09513354,
       47.39727268, 47.43274079, 48.27686342, 49.08834794, 47.47113644,
       48.97570642, 47.03455432, 48.52027703, 46.99132543, 48.22149917,
       48.0596431 , 48.30744246, 47.66401684, 46.48155215, 46.43167903])

In [43]:
# min -max normalization
arr_norm= (arr - arr.min(axis=0))/(arr.max(axis=0)- arr.min(axis=0))
arr_norm

array([[0.36363636, 0.78787879, 0.86868687, ..., 0.48484848, 0.97979798,
        0.14141414],
       [0.55555556, 0.47474747, 0.36363636, ..., 0.7979798 , 0.75757576,
        0.16161616],
       [0.67676768, 0.85858586, 0.58585859, ..., 0.58585859, 0.50505051,
        0.76767677],
       ...,
       [0.8989899 , 0.11111111, 0.80808081, ..., 0.55555556, 0.67676768,
        0.98989899],
       [0.54545455, 0.67676768, 0.54545455, ..., 0.01010101, 0.68686869,
        0.21212121],
       [0.90909091, 0.3030303 , 0.24242424, ..., 0.96969697, 0.6969697 ,
        0.76767677]])

In [44]:
# array with bias column
arr_bias=np.hstack([np.ones((arr.shape[0],1)),arr])

### Question 4: Eigen Decomposition and PCA with NumPy

You are given a dataset represented as a 2D NumPy array X of shape (500, 20) where each row is a data sample and each column is a feature. Perform Principal Component Analysis (PCA) without using sklearn, only with NumPy:

1. Standardize the data (zero mean, unit variance).

2. Compute the covariance matrix of the standardized data.

3. Perform eigen decomposition of the covariance matrix.

4. Sort eigenvalues and eigenvectors in descending order.

5. Project the data onto the top 3 principal components.

In [51]:
np.random.seed(42)
arr=np.random.randn(500,20)

In [52]:
# standardization
arr_std=(arr - arr.mean(axis=0))/arr.std(axis=0)
arr_std

array([[ 0.46591144, -0.1899865 ,  0.6776409 , ...,  0.31995548,
        -0.87774831, -1.50286433],
       [ 1.42053702, -0.27905449,  0.10115554, ..., -1.8446737 ,
        -1.29242007,  0.19737897],
       [ 0.70409371,  0.12515143, -0.08086064, ..., -0.27353972,
         0.34534555,  1.02013618],
       ...,
       [-0.58253468,  1.78429623,  2.04341991, ..., -0.96406205,
         0.66057612,  0.43939286],
       [-1.07832236, -0.84753023,  0.71818984, ..., -0.83680995,
        -0.9810422 , -1.87019672],
       [-0.46267924, -0.56194248,  0.55666086, ..., -0.65060663,
         0.50769816,  0.67023612]])

In [53]:
arr_std.mean(0)

array([-2.63122857e-17, -7.06101844e-17, -4.26325641e-17, -2.29261055e-17,
        1.02140518e-17, -2.73114864e-17,  2.66453526e-18, -4.13002965e-17,
        1.73194792e-17,  2.06501483e-17, -3.28626015e-17,  9.15933995e-18,
        1.15463195e-17, -7.99360578e-18, -1.64313008e-17, -2.22044605e-17,
       -2.39808173e-17,  1.62092562e-17,  2.42028619e-17,  4.48530102e-17])

In [54]:
# compute covarience
arr_cov=np.cov(arr_std.T)

In [57]:
### calculate eigen decomposition
eigenvalue, eigenvectors = np.linalg.eigh(arr_cov)

In [58]:
# sort eigen vectors
idx= np.argsort(eigenvalue)[::-1]
eigenvalue =eigenvalue[idx]
eigenvectors=eigenvectors[:,idx]

In [59]:
# project data onto top 3 principal components
X_pca= arr_std @ eigenvectors[:,:3]

In [60]:
# Outputs for validation
print("Covariance matrix shape:", arr_cov.shape)
print("Top 5 eigenvalues:", eigenvalue[:5])
print("Eigenvectors shape:", eigenvectors.shape)
print("Transformed dataset shape:", X_pca.shape)

Covariance matrix shape: (20, 20)
Top 5 eigenvalues: [1.35501731 1.27913733 1.25836532 1.207866   1.17677586]
Eigenvectors shape: (20, 20)
Transformed dataset shape: (500, 3)


### Q5: Convolution Implementation with NumPy
#### Problem Statement

Implement a 2D convolution operation from scratch (without using libraries like scipy.signal.convolve2d).

1. Input: A 2D matrix (say 6x6) and a kernel (say 3x3).

2. Output: A convolved 2D matrix.

In [61]:
# 1. Imput matrix
X = np.array([
    [1, 2, 3, 0, 0, 1],
    [0, 1, 2, 3, 1, 0],
    [1, 0, 1, 2, 3, 1],
    [2, 1, 0, 1, 2, 3],
    [0, 1, 2, 1, 0, 1],
    [1, 2, 3, 2, 1, 0]
])

# 2. Kernel
K=np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])


# 3. Convolutional implementation
def conv2d(X, K):
    X_h, X_w = X.shape
    K_h, K_w = K.shape
    out_h = X_h - K_h +1
    out_w = X_w - K_w +1

    # Initialize output
    out=np.zeros((out_h, out_w))

    for i in range(out_h):
        for j in range(out_w):
            region = X[i:i+K_h, j:j+K_w]
            out[i, j] = np.sum(region*K)
    return out


output = conv2d(X, K)

print("Input shape:", X.shape)
print("Kernel shape:", K.shape)
print("Output shape:", output.shape)
print("Convolved output:\n", output)

Input shape: (6, 6)
Kernel shape: (3, 3)
Output shape: (4, 4)
Convolved output:
 [[-4. -2.  2.  3.]
 [ 0. -4. -3.  2.]
 [ 0. -2. -2. -1.]
 [-2.  0.  2.  0.]]


### Q6. Matrix Eigendecomposition

📌 Problem Statement:
Given a symmetric matrix (say, size 4×4), perform an eigendecomposition using NumPy and validate the result.

1. Compute the eigenvalues and eigenvectors of the matrix.

2. Reconstruct the original matrix using the decomposition formula:

𝐴= 𝑉Λ𝑉𝑇
where:
A = original matrix
V = eigenvectors
Λ = diagonal matrix of eigenvalues

3. Verify your reconstruction by checking if the difference between the original and reconstructed matrix is close to zero (use np.allclose).

In [64]:
# 1. create numpy array

X = np.array([[6, 2, 1, 0],
              [2, 3, 1, 0],
              [1, 1, 1, 0],
              [0, 0, 0, 5]])

X_std = (X- X.mean(axis = 0))/X.std(axis =0)

cov_matrix = np.cov(X_std.T)

eigenvalue, eigenvectors = np.linalg.eigh(cov_matrix)

idx= np.argsort(eigenvalue)[::-1]
eigenvalue = eigenvalue[idx]
eigenvectors=eigenvectors[:,idx]

np.allclose(eigenvalue, eigenvectors @ np.diag(eigenvalue) @ eigenvalue.T)

False

### Q7: Singular Value Decomposition (SVD)

You are given a 5×3 random matrix.

Task:

1. Perform Singular Value Decomposition (SVD) using NumPy.

2. Verify that A=UΣVT

3. Reconstruct the matrix using only the top 2 singular values and compare it with the original (approximation).

In [66]:
A=np.random.randint(1,10,(5,3))