### Numpy revision Tutorial

In [1]:
import numpy as np

In [4]:
a=np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
a.shape

(2, 3)

In [8]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [9]:
a[0]

1

In [10]:
a[0]=10
print(a)

[10  2  3  4  5  6  7]


In [11]:
a[:3]

array([10,  2,  3])

In [12]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
a[1,3]

8

In [15]:
a.ndim # number of dimention of an array

2

In [17]:
a.shape # shape of an array

(3, 4)

In [18]:
a.size # size of an array

12

In [19]:
a.dtype # datatype of an array

dtype('int32')

### Create a basic array

In [21]:
a = np.zeros(5) # creating an array of size 5 with all number is zero
print(a)

[0. 0. 0. 0. 0.]


In [22]:
b=np.ones(3)
print(b)

[1. 1. 1.]


In [24]:
c= np.empty(3) # creat an array empty element
print(c)

[1. 1. 1.]


In [25]:
d=np.arange(5) # create the numpy array with range
print(d)

[0 1 2 3 4]


In [26]:
e=np.arange(2,9,2) # first, last, step
print(e)

[2 4 6 8]


In [32]:
f= np.linspace(0,15,num=6)
print(f)

[ 0.  3.  6.  9. 12. 15.]


In [36]:
g= np.ones(2, dtype=np.int32)
print(g)

[1 1]


In [37]:
g.dtype

dtype('int32')

### Removing and Sorting

In [41]:
arr=np.array([3,2,1,5,6,4,8])
print(arr)
arr2=np.sort(arr)
print(arr2)


[3 2 1 5 6 4 8]
[1 2 3 4 5 6 8]


In [46]:
arr1 = np.array([1,2,3,4])
arr2 =np.array([5,6,7,8])
arr3= np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [52]:
x= np.array([[1,2],[3,4]])
y = np.array([[5,6]])
z= np.concatenate((x,y),axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
z.size

6

In [57]:
a=np.arange(6)
print(a)
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [58]:
data=np.arange(6)
data[1]

1

In [59]:
data[0:2]

array([0, 1])

In [60]:
data[1:]

array([1, 2, 3, 4, 5])

In [61]:
data[-2:]

array([4, 5])

In [65]:
data[-2:]

array([4, 5])

In [66]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<6])

[1 2 3 4 5]


In [67]:
five_up= (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [70]:
list(zip(b[0], b[1]))

[(0, 2), (1, 3)]

### Create array with existing data

In [71]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=a[3:8]
print(arr1)

[4 5 6 7 8]


In [72]:
x=np.arange(1,25).reshape(2,12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [73]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
b1=a[0,:]
print(b1)

[1 2 3 4]


In [76]:
b1[0]=99
print(b1)

[99  2  3  4]


In [77]:
print(a)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
b2=a.copy()

In [79]:
### Binary array operations

In [81]:
data=np.array([1,2])
one=np.ones(2, dtype=int)
data+one

array([2, 3])

In [82]:
data-one

array([0, 1])

In [83]:
data/one

array([1., 2.])

In [84]:
a=np.array([1,2,3,4])
a.sum()

10

In [86]:
b=np.array([[1,1],[2,2]])
print(b.sum(axis=0))
print(b.sum(axis=1))

[3 3]
[2 4]


In [87]:
data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

In [88]:
print(data.max())
print(data.min())
data.sum()

2.0
1.0


3.0

In [90]:
data=np.array([[1,2],[3,4],[5,6]])
one=np.array([[1,1]])
data+one

array([[2, 3],
       [4, 5],
       [6, 7]])

In [91]:
a=np.array([11,12,11,13,14,15,16,14,13,15])
print(np.unique(a))

[11 12 13 14 15 16]


In [92]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [96]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [97]:
arr=np.array([1,2,3,4,5,6,7,8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [98]:
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [104]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [100]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [103]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [105]:
x=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
a1=x.flatten()
a1[0]=99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
